{% set version = "4.3.0" %}

package:
  name: genomekit
  version: {{ version }}

source:
  url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9264ae39316cc087a402e705ca0962e100f674a647ec15788ee25eb907cafe36

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: true  # [py>310 or py<38]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - appdirs
    - fmt
    - numpy  # [not win or py>38]
     # avoid build failure on Windows
    - numpy >=1.18.0,<1.19.0  # [win and py==38]
    - typing-extensions
    - zlib
    - python {{ python }}
    - pip

  run:
    - appdirs
    - crc32c
    - google-cloud-storage >=2.10.0
    - {{ pin_compatible('numpy') }}
    - typing-extensions
    - importlib-metadata
    - tqdm
    - python {{ python }}

test:
  imports:
    - genome_kit
  requires:
    - pytest-cov
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - python -m unittest discover

about:
  doc_url: https://genomekit.readthedocs.io/
  home: https://github.com/deepgenomics/GenomeKit
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: GenomeKit is a Python library for fast and easy access to genomic resources such as sequence, data tracks, and annotations.

extra:
  recipe-maintainers:
    - ovesh
