{% set version = "6.1.1" %}

package:
  name: genomekit
  version: {{ version }}

source:
  url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7111f268aa788a76ad5787b327e0fb737d67ee8e6851e4bea93ac6b89b2d3df0

build:
  number: 2
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: true  # [py>312 or py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy <2.0dev0                         # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]

  host:
    - appdirs
    - fmt
    - numpy <2.0dev0
    - typing-extensions
    - zlib
    - python {{ python }}
    - pip
    - setuptools

  run:
    - appdirs
    - google-cloud-storage >=2.10.0
    - boto3
    # https://github.com/conda/conda/issues/13619
    - pyopenssl >=23.2.0
    - typing-extensions
    - importlib-metadata
    - tqdm
    - python {{ python }}

test:
  imports:
    - genome_kit
  requires:
    - pytest-cov
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - python -m unittest discover

about:
  doc_url: https://deepgenomics.github.io/GenomeKit/
  home: https://github.com/deepgenomics/GenomeKit
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: GenomeKit is a Python library for fast and easy access to genomic resources such as sequence, data tracks, and annotations.

extra:
  recipe-maintainers:
    - s22chan
    - ovesh
