{% set version = "5.2.2" %}

package:
  name: genomekit
  version: {{ version }}

source:
  url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2f8e7fe57f11bbbecc396674d03d21d471de9319dfab6725a483f131ae744046

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: true  # [py>310 or py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]

  host:
    - appdirs
    - fmt
    - numpy  # [not win or py>38]
     # avoid build failure on Windows
    - numpy >=1.18.0,<1.19.0  # [win and py==38]
    - typing-extensions
    - zlib
    - python {{ python }}
    - pip
    - setuptools

  run:
    - appdirs
    - google-cloud-storage >=2.10.0
    - {{ pin_compatible('numpy') }}
    - typing-extensions
    - importlib-metadata
    - tqdm
    - python {{ python }}

test:
  imports:
    - genome_kit
  requires:
    - pytest-cov
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - python -m unittest discover

about:
  doc_url: https://genomekit.readthedocs.io/
  home: https://github.com/deepgenomics/GenomeKit
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: GenomeKit is a Python library for fast and easy access to genomic resources such as sequence, data tracks, and annotations.

extra:
  recipe-maintainers:
    - s22chan
    - ovesh
