{% set version = "4.2.1" %}

package:
  name: genomekit
  version: {{ version }}

source:
  url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8793fb15cba3f572879996d47d6320c8ec983995c6f713848f53ca5dae7e5844

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  # Py3.9 includes backwards-incompatible changes to the C extension API
  # See https://docs.python.org/3/whatsnew/3.9.html#changes-in-the-c-api
  # TODO Add support for more python versions
  skip: true  # [py!=38]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - appdirs
    - fmt
    - numpy  # [not win]
     # avoid build failure on Windows
    - numpy >=1.18.0,<1.19.0  # [win]
    - typing-extensions
    - zlib
    - python
    - pip

  run:
    - appdirs
    - crc32c
    - google-cloud-storage >=2.10.0
    - {{ pin_compatible('numpy') }}
    - typing-extensions
    - importlib-metadata
    - tqdm
    - python

test:
  imports:
    - genome_kit
  requires:
    - pytest-cov
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - python -m unittest discover

about:
  doc_url: https://genomekit.readthedocs.io/
  home: https://github.com/deepgenomics/GenomeKit
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: GenomeKit is a Python library for fast and easy access to genomic resources such as sequence, data tracks, and annotations.

extra:
  recipe-maintainers:
    - ovesh
